// frontend/src/components/Navbar.vue
<template>
	<nav
		v-if="this.$route.path != '/login'"
		role="navigation"
		class="navbar navbar-expand-lg navbar-dark px-4"
	>
		<router-link class="navbar-brand" to="/">
			<img src="../assets/orange_logo.svg" alt="Orange Logo" />
		</router-link>
		<button
			class="navbar-toggler"
			type="button"
			data-toggle="collapse"
			data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<!-- Boosted mod: active class on link -->
					<router-link class="nav-link active" to="/" aria-current="page">
						Home <span class="sr-only">(current)</span>
					</router-link>
				</li>
				<li class="nav-item">
					<router-link class="nav-link" to="/Technologies">
						Technologies
					</router-link>
				</li>
				<li class="nav-item">
					<router-link class="nav-link" to="/AboutUs">
						About Us
					</router-link>
				</li>
				<li class="nav-item">
					<router-link class="nav-link" to="/ContactUs">
						Contact Us
					</router-link>
				</li>
			</ul>
			<form class="form-inline">
				<router-link class="btn btn-secondary btn-inverse" to="/login">
					Sign In
				</router-link>
			</form>
		</div>
	</nav>
</template>

<script>
import { store } from "../store/store";

export default {
	name: "Navbar",
	data() {
		return {
			store: store,
		};
	},
};
</script>

// frontend/src/component/navbar.jsx




export default function Navbar() {

    return (

        <nav role="navigation" className="navbar navbar-expand-lg navbar-dark p-2">
            <a className="navbar-brand" href="/home">Navbar</a>
            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="/homenavbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon" />
            </button>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
                <ul className="navbar-nav mr-auto">
                    <li className="nav-item">
                        {/* Boosted mod: active class on link */}
                        <a className="nav-link active" href="/home" aria-current="page">Home <span className="sr-only">(current)</span></a>
                    </li>
                    <li className="nav-item">
                        <a className="nav-link" href="/home">Link</a>
                    </li>
                    <li className="nav-item dropdown">
                        <a className="nav-link dropdown-toggle" href="/home" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                </a>
                        <div className="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a className="dropdown-item" href="/home">Action</a>
                            <a className="dropdown-item" href="/home">Another action</a>
                            <div className="dropdown-divider" />
                            <a className="dropdown-item" href="/home">Something else here</a>
                        </div>
                    </li>
                    <li className="nav-item">
                        <a className="nav-link disabled" href="/home" tabIndex={-1} aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form className="form-inline my-2 my-lg-0">
                    <input className="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" />
                    <button className="btn btn-secondary btn-inverse my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    );
}
